-- C H P에서 C-h로 기간 알아내고, c-p 기간과 타입으로 할인율 알아내기

    SELECT T.HISTORY_ID, PERIOD * DAILY_FEE * (100-IFNULL(TRIM('%' FROM DISCOUNT_RATE), '0'))*0.01 AS FEE
    FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN P RIGHT JOIN (
        SELECT HISTORY_ID, DAILY_FEE, DATEDIFF(END_DATE,START_DATE)+1 PERIOD
        FROM CAR_RENTAL_COMPANY_CAR C JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY H using (CAR_ID)
        WHERE CAR_TYPE = '트럭'
    ) T ON P.CAR_TYPE = '트럭' AND P.DURATION_TYPE = CASE
    WHEN PERIOD >= 90 THEN '90일 이상'
    WHEN PERIOD >= 30 THEN '30일 이상'
    WHEN PERIOD >= 7 THEN '7일 이상'
    ELSE NULL
    END
    ORDER BY FEE DESC, HISTORY_ID DESC